spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?user=root
    username: root
    password: alka@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true